version: '3.8'

services:
  homecleanerbot:
    build: .
    container_name: homecleanerbot
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./maps:/home/ros2_ws/maps
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /home/ros2_ws/install/setup.bash &&
        ros2 launch auto_robot home_cleaner.launch.py"